### ISSUE TITLE
Can i create android bundle from this extention?

### ISSUE THREAD

**Issue by MasihAkbari** [defold/extension-iap#5]
hi, I wanted to test this extension, so can I create an android bundle from this project directly? or do I have to add this to a separate project and create a bundle from that?
I tried to create an android bundle from this project directly and gets some errors:
![image](https://user-images.githubusercontent.com/8469800/65814966-ed8a1f00-e1f5-11e9-856b-beaa80666762.png)
I can't get anywhere when I double click on errors so I don't know where are these errors come from.
how can I test this extension?

**Comment by MasihAkbari** [comment]
I test this again with adding it to another project and make a bundle, and the same errors pop out, so am I need to do something before creating a bundle with this extension?

**Comment by AGulev** [comment]
The issue you found do not relate to this extension and will be solved in the next version of Defold 1.2.163
https://forum.defold.com/t/android-bundling-error-with-app-manifest-issue-4458/63350

You can't build this build `iap-extension` with the current version of Defold, because right now we are working on the extraction this part of the engine right now. It will be possible to build this extension starting version 1.2.163.
